### ISSUE TITLE
URL should change when state changes

### ISSUE THREAD

**Issue by HosseinYousefi** [HosseinYousefi/yeet#5]
Not all state changes happen with `context.yeet`. Some of these, for example swiping through a page controller might change the state of the page, and we might want to update the url, there should be a very easy way to do this.

**Comment by M4RZB4Ni** [comment]
I have this issue too !

**Comment by HosseinYousefi** [comment]
This has been solved in 0.4.3. You can use `context.changePath` to change the path of the top page to reflect the state better.
